version: '3'
services:
   mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=backend_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - database-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  covid-app:
    build: ./covid-app
    container_name: covid-app
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=backend-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    links:
      - postgres

   covid-ui:
    build: ./covid-ui
    container_name: covid-ui
    ports:
      - 4200:80
    links:
      - covid-app

volumes:
  database-data: