version: '3'
services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=covid_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  covid-service:
    image: ntshuxeko/covid-service:latest
    container_name: covid-service
    ports:
      - 8081:8081

  covid-ui:
    image: ntshuxeko/covid-ui:latest
    container_name: covid-ui
    ports:
      - 4300:80
        
volumes:
  db:
