jwt:
    expiration:
        ms: 1800000
    secret: COVID19928089FA5F1B21AB01B65D37B71DD6F54526EE33A8AA7CC5B72A7B766F073D9CWEBAPP
server:
    port: 8081
    servlet:
        context-path: /covid
spring:
    datasource:
        url: jdbc:mysql://13.59.127.196:3306/covid_db
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER


